CODE = $(filter %.cs,$^)
DLLS = $(addprefix -reference:,$(filter %.dll,$^))
MKEXE = mcs -target:exe -out:$@ $(DLLS) $(CODE)
MKDLL = mcs -target:library -out:$@ $(DLLS) $(CODE)

matrix.dll: matrix.cs vector.dll ; $(MKDLL)

vector.dll: vector.cs ; $(MKDLL)
